### ISSUE TITLE
PathSum

### ISSUE THREAD

**Issue by markusbaumeister** [markusbaumeister/simplicial-surfaces#108]
Document and implement sums of vertex-edge-paths and edge-face-paths.

**Comment by MeikeWeiss** [comment]
Which sum do you mean?

**Comment by markusbaumeister** [comment]
This refers to the concatenation of paths. If you have two paths v -> w and w -> z, they can be combined into a path v -> z.
You are correct to notice that "sum" is not the best term here (since you cannot "add" to arbitrary paths). Thus, "concatenation" is probably a better name.
