### ISSUE TITLE
Missing Package dependency of package fga

### ISSUE THREAD

**Issue by TomGoertzen** [markusbaumeister/simplicial-surfaces#143]
The package uses the function BoundPositions of fga in gap/ColouredComplexes/edgeColouring.gi;

This could be resolved in one of the following ways

1. Add fga to the list of necessary packages
2. Use the function __SIMPLICIAL_BoundPositions instead

I think the second option might be a bit better

**Comment by markusbaumeister** [comment]
Alternatively, one could switch to the GAP-method `PositionsBound`, compare https://github.com/gap-system/gap/pull/2223
